### ISSUE TITLE
Failed to restart clamav-daemon.service: Interactive authentication required.

### ISSUE THREAD

**Issue by MrX123123** [extremeshok/clamav-unofficial-sigs#359]
Hi all,

since I updated to the latest version (v7.2.2) I am receiving hourly error messages from my server complaining about "Failed to restart clamav-daemon.service: Interactive authentication required.". Debian 9.13 is running on the server.
 
This is the error message:

=====================================
ERROR: Failed to reload, trying again
=====================================
=================================================
ERROR: Failed to reload, forcing clamd to restart 
=================================================
Failed to restart clamav-daemon.service: Interactive authentication required.
See system logs and 'systemctl status clamav-daemon.service' for details.

and systemd message:

`# systemctl status clamav-daemon.service
● clamav-daemon.service - LSB: ClamAV daemon
   Loaded: loaded (/etc/init.d/clamav-daemon; generated; vendor preset: enabled)
  Drop-In: /etc/systemd/system/clamav-daemon.service.d
           └─extend.conf
   Active: active (exited) since Tue 2020-12-29 22:05:29 CET; 12min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 9826 ExecStop=/etc/init.d/clamav-daemon stop (code=exited, status=0/SUCCESS)
  Process: 9835 ExecStart=/etc/init.d/clamav-daemon start (code=exited, status=0/SUCCESS)
  Process: 9832 ExecStartPre=/bin/chown clamav /run/clamav (code=exited, status=0/SUCCESS)
  Process: 9829 ExecStartPre=/bin/mkdir /run/clamav (code=exited, status=1/FAILURE)
 Main PID: 7927 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/clamav-daemon.service

Dez 29 22:05:29 s181 systemd[1]: Starting LSB: ClamAV daemon...
Dez 29 22:05:29 s181 mkdir[9829]: /bin/mkdir: cannot create directory ‘/run/clamav’: File exists
Dez 29 22:05:29 s181 systemd[1]: Started LSB: ClamAV daemon.
`

Found a similar error message here from 2017 on centos, but nothing helped so far. https://github.com/extremeshok/clamav-unofficial-sigs/issues/186

Maybe you have an idea or solution?

Br
Jan

**Comment by extremeshok** [comment]
Would appear the user does not have permission to restart the service.

**Comment by perplexityjeff** [comment]
@MrX123123 Could you give an update about the matter?

**Comment by MrX123123** [comment]
Hi perplexityjeff,
thanks for asking. Couldn't find the root cause. Maybe influenced by rspamd.
Br

**Comment by perplexityjeff** [comment]
> Hi perplexityjeff,
> thanks for asking. Couldn't find the root cause. Maybe influenced by rspamd.
> Br

But the issue has since been resolved?

**Comment by MrX123123** [comment]
Well, I removed clam-av and installed rspamd.

**Comment by perplexityjeff** [comment]
@MrX123123 What version of ClamAV where you using?

**Comment by MrX123123** [comment]
Hi, 
please see below.

> dpkg -l|grep clam
ii  clamav                                0.102.4+dfsg-0+deb10u1                                                   amd64        anti-virus utility for Unix - command-line interface
ii  clamav-base                           0.102.4+dfsg-0+deb10u1                                                   all          anti-virus utility for Unix - base package
ii  clamav-daemon                         0.102.4+dfsg-0+deb10u1                                                   amd64        anti-virus utility for Unix - scanner daemon
ii  clamav-freshclam                      0.102.4+dfsg-0+deb10u1                                                   amd64        anti-virus utility for Unix - virus database update utility
ii  clamav-milter                         0.102.4+dfsg-0+deb10u1                                                   amd64        anti-virus utility for Unix - sendmail integration
ii  clamdscan                             0.102.4+dfsg-0+deb10u1                                                   amd64        anti-virus utility for Unix - scanner client
ii  libclamav9:amd64                      0.102.4+dfsg-0+deb10u1                                                   amd64        anti-virus utility for Unix - library

**Comment by extremeshok** [comment]
Can't replicate the issue. 

Please open and link this issue if the issue re-appears.

**Comment by devchimpa** [comment]
Hello, everyone!
I had a similar problem:

Active: active (running) since Tue 2024-04-02 11:54:55 -03; 35s ago
     Docs: man:clamd(8)
           man:clamd.conf(5)
           https://docs.clamav.net/
  Process: 11154 ExecStartPre=/bin/mkdir /run/clamav (code=exited, status=1/FAILURE)
  Process: 11161 ExecStartPre=/bin/chown clamav /run/clamav (code=exited, status=0/SUCCESS)
 Main PID: 11163 (clamd)
    Tasks: 1 (limit: 4700)
   Memory: 969.4M
   CGroup: /system.slice/clamav-daemon.service
           └─11163 /usr/sbin/clamd --foreground=true
           

And I solved following this steps:

1 - In  "/run/clamav" I moved the file "clam.ctl"  for "/tmp"

2 - I removed the directory "clamav" from "/run"

3 - systemctl start clamav-daemon  ( the failed persisted, but the directory "/run/clamav" was createad again )

4 - I copied "clam.ctl" from "/tmp" for "/var/run/clamav"

5 -  systemctl restart clamav-daemon


 systemctl status clamav-daemon
● clamav-daemon.service - Clam AntiVirus userspace daemon
   Loaded: loaded (/lib/systemd/system/clamav-daemon.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/clamav-daemon.service.d
           └─extend.conf
   Active: active (running) since Tue 2024-04-02 11:57:43 -03; 1h 0min ago
     Docs: man:clamd(8)
           man:clamd.conf(5)
           https://docs.clamav.net/
  Process: 32610 ExecStartPre=/bin/mkdir /run/clamav (code=exited, status=0/SUCCESS)
  Process: 32623 ExecStartPre=/bin/chown clamav /run/clamav (code=exited, status=0/SUCCESS)
 Main PID: 32624 (clamd)
    Tasks: 2 (limit: 4700)
   Memory: 1.2G
   CGroup: /system.slice/clamav-daemon.service
           └─32624 /usr/sbin/clamd --foreground=true


I don't know why exactly it's works, but solved my problem.

**Comment by HeinrickCamargos** [comment]
NICE!!!
