### ISSUE TITLE
make cron job silent

### ISSUE THREAD

**Issue by kosli** [extremeshok/clamav-unofficial-sigs#38]
Currently the included cron job produces some output that is being mailed because only the stdout is sent to /dev/null but not stderr

So it should probably be 
`45 * * * * root /bin/bash /usr/local/bin/clamav-unofficial-sigs.sh  >/dev/null 2>&1 `

**Comment by olivier2557** [comment]
Same remark.

Even with $comment_silence="yes" the cron will output:

`################################################################################`
 `eXtremeSHOK.com ClamAV Unofficial Signature Updater`
 `Version: v4.9.2 (02 December 2015)`
 `Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com`
`################################################################################`
`==========================================================`
`Loading config: /usr/local/etc/clamav-unofficial-sigs.conf`
`==========================================================`

Which make sens because it is printed before the config file is loaded, so before the silence option is set.

Running cron with a redirection to /dev/null is not a good solution, because you will not see the notifications when there is an error.

**Comment by extremeshok** [comment]
I have a fix for that which I used for one of my other scripts

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by nerijus** [comment]
Yes, it would be nice if cron script sent the email (i.e. generate output) only when there are errors.

**Comment by extremeshok** [comment]
Will be in the next update which is either today or tomorrow

**Comment by extremeshok** [comment]
Fixed via 556c063200707d1058d5e8f3a16b77eb34d7dda0
