### ISSUE TITLE
RPM packages for CentOS 7.

### ISSUE THREAD

**Issue by prupert** [extremeshok/clamav-unofficial-sigs#78]
Please build RPM packages for easy install of clamav-unofficial-sigs.

**Comment by prupert** [comment]
Just wondering if there is any update regarding package support for CentOS.

**Comment by donmichelangelo** [comment]
I don't speak for extremshok, but CentOS packages would only work/make sense if someone/extremeshok would take over the package maintenance of clamav-unofficial-sigs at the EPEL Repo.

The next point/problem is, that it is already possible to easily deploy and uninstall clamav-unofficial-sigs via the CLI switches...

So it's actually counterproductive to create RPMs for a software that supports less or more it's own install and uninstall routines because you would also have to patch these routines out.

Imagine this: You install the unofficial sigs via a RPM and you call --remove-script or --install-all but the clamav-unofficial-sigs will still be listed in your RPM database... not cool...

**Comment by prupert** [comment]
It is never counterproductive to create packages for software. Software should always be installed via packages on any Linux distribution. On the contrary, it does not make sense to create your own manual scripted way to install or uninstall software.

**Comment by nerijus** [comment]
@prupert +1

**Comment by donmichelangelo** [comment]
Of course it is never counterproductive to create packages for software.
I also never claimed that but it depends imho on the circumstances ...

>  Software should always be installed via packages on any Linux distribution.

I agree with you, but as I already told you, the --remove-scripts and --install-all shouldn't exist in this case. 

Dunno how others think about this...

**Comment by extremeshok** [comment]
Set a "pkg_mgr" and "pkg_rm" options in the os.conf and the remove function is disabled.
````
  if [ -n "$pkg_mgr" ] || [ -n "$pkg_rm" ] ; then
    echo "This script (clamav-unofficial-sigs) was installed on the system via '$pkg_mgr'"
    exit 1
  fi
````
I have updated the code to disable the install routines as well. 0168cb38853e0503e59a6c698047eed2876e8ab4 

As to "Software should always be installed via packages on any Linux distribution"... I will agree to disagree.

Automatic updates will be rolled out in version 5.5

**Comment by donmichelangelo** [comment]
@extremeshok 
Looks like a compromise for package maintainers...
Would you also implement an option to disable automatic updates?

**Comment by extremeshok** [comment]
Would you also implement an option to disable automatic updates?
Yes
And i will aslo rewrite it so the options are hidden from the user when installed via a package.

**Comment by SpareSimian** [comment]
I'm working on an updated RPM package for use with CentOS 6, based on Fedora's RPM. I think the install options should remain available post-packaging. The man page won't need to be regenerated, but the cron and logrotate files can be treated as outputs to be regenerated whenever the end user changes settings. Default files would be provided by the package. 

One feature I'd like to see added is a virtual packaging root directory which is used to assemble the output files (man, cron, logrotate) into a directory structure simulating the final installation. This directory is provided by the packaging system (eg. rpmbuild). (Example: /var/tmp/clamav-unofficial-sigs, under which there would be etc, bin, lib, and var directories to "install" into.) The script should strip out this prefix when writing the logrotate and cron files. 

Also, the script should tolerate the absence of the clam user when writing the files without root permission. The packager will not be running as root and may not have the clamav package installed. (The script doesn't need it for packaging, only for non-packaged installation. The package system will assign ownership to files during "real" installation.)

**Comment by donmichelangelo** [comment]
@extremeshok 

Here is my advice/thoughts after some fiddling with the latest release:

1. get rid of this extraction of the config/sys files from within the script itself. Return to the way like these files were distributed before version 5.1. 

2. Refactor the script so that it is possible to override the vars for cron.d/logrotate (and so on) from the CLI.
Therefore it isn't even necessary to introduce switches to the script itself. I can work pretty well with exported variables which the script will then use, but currently several functions and also the way how they are arranged within the script doesn't allow something like that.


However, I would prefer the first option. The first solution would also reduce the size of the script itself.

**Comment by extremeshok** [comment]
will work on this tomorrow

**Comment by SpareSimian** [comment]
[Here's my RPM spec file](http://pastebin.com/xqWYmR0j), based on the latest Fedora spec file. The most interesting parts are the %install and %files sections. The %install section lays out the file structure in a simulated root hiearchy. The %files section applies the metadata (ownership and permissions) when the package is installed later with root privileges.

**Comment by donmichelangelo** [comment]
dude, you can change the entire file structure in the %prep step.

There is no need to force extremshok to any layout. Just make it possible to either extract the necessary config files from the shell script itself or as I stated already, revert the config file deployment to *before* version 5.1.

Since I'am a not familar with packaging .deb packages, I can't talk for .deb packagers and if they need any changes, but for RPM based distributions that's all what I need.

**Comment by SpareSimian** [comment]
With RPM, the %prep step unpacks the tarball and applies distro-specific patches. The %install step is responsible for establishing the file structure. My script simply sets a custom config and then invokes the extremshok script to put the files in the simulated root. But those files contain hard-coded references to the simulated root, not the final "real" location. So I have to do some sed magic to remove those references.

**Comment by extremeshok** [comment]
If you have a shell script to build, I can use that with travis to automatically build and host the latest release.

**Comment by lberra** [comment]
i reworked @SpareSimian spec file a bit and tested on centos7, it should work on any recent fedora and maybe on centos6 (untested)
it is attached [here](https://gist.github.com/lberra/d414e6b6c6c4fa0a7532d3d65d3ddade)

1. on centos7 i use the systemd service vs the cron file
- i changed the unit file to run as clamupdate user, i am using runas because next step could be reading the configuration files and dynamically changing user.

2. in order to install i create a fake install conf and run the install routines against that, so no need to sed after install

3. on uninstall i read the purge.txt file and remove the file listed there,
-  since purge.txt contains patterns i use a for loop on cat xxx instead of a read loop. you should fix it as well in the main script.
- i also check that files are owned by clamupdate, since the uninstall process is privileged

**Comment by lberra** [comment]
i dont have a build script but i usually do something like:

```
  before_script:
    - yum -y install epel-release
    - yum -y update
    - yum -y install @buildsys-build
    - tar zcvf clamav-unofficial-sigs-version.tar.gz <your dist dir>
    script:
    - rpmbuild --define "_sourcedir $PWD" --define "_topdir $PWD" -bs clamav-unofficial-sigs.spec
    - yum-builddep -y SRPMS/*.rpm
    - rpmbuild --define "_topdir $PWD" --rebuild SRPMS/*.rpm
 
```

**Comment by extremeshok** [comment]
@SpareSimian @didier13150 thanks for this.

Im preparing a large update for a v6.. fixing all outstanding and known issues.
