### ISSUE TITLE
cron rsync error

### ISSUE THREAD

**Issue by Gazoo** [extremeshok/clamav-unofficial-sigs#86]
After setting this up on Centos 7 the clamav-unofficial-sigs.sh cron gives this error:

@ERROR: max connections (160) reached -- try again later
rsync error: error starting client-server protocol (code 5) at main.c(1516) [Receiver=3.0.9]

**Comment by extremeshok** [comment]
usually thats because the server is overloaded. usually can be ignored, unless it does that for every run.

**Comment by Gazoo** [comment]
>  usually thats because the server is overloaded. 
Our server isn't overload as the clamav-unofficial-sigs cron is the only thing actually using rsync. Do we know why it goes over the default rsync limits?

**Comment by reneschuster** [comment]
I had the same problems with the default cron minute value for many days.
Some weeks ago I changed the minutes value and the problem was gone. 

Change 
`45 * * * * root /bin/bash /usr/local/bin/clamav-unofficial-sigs.sh  > /dev/null`
to e.g.
`28 * * * * root /bin/bash /usr/local/bin/clamav-unofficial-sigs.sh  > /dev/null`

@extremeshok 
A random value for the cron would also be great. Or increase the random value for the execution time. I assume 10 min is too low.

**Comment by reneschuster** [comment]
@extremeshok 
Forget it, I just have seen that it is already implemented in the latest version.
https://github.com/extremeshok/clamav-unofficial-sigs/blob/master/clamav-unofficial-sigs.sh#L233

**Comment by Gazoo** [comment]
@reneschuster  I'll wait for the 5.1 release then and report back if I still see the issue. Thanks for your help!

**Comment by extremeshok** [comment]
Run the script with the --install-cron , and the values will be random. 

The latest release auto generates the cron file
